name: 'Store Playwright Results'
description: 'Store Playwright Results'
inputs:
  provider-deployment-url:
    description: 'The deployment URL to test with'
    required: true
  provider:
    description: 'Which next deployment provider is used'
    required: true
runs:
  using: "composite"
  steps:
    - name: Run E2E Tests on Netlify URL
      run: REMOTE_PROVIDER=${{ inputs.provider }} yarn e2e
      shell: bash
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ inputs.provider-deployment-url }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-${{ inputs.provider }}
        path: playwright-report/
        retention-days: 10
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots-${{inputs.provider}}
        path: tests/e2e/__screenshots__/${{inputs.provider}}
        retention-days: 10
